-- [M2S07] Ex. 01 - Sistema de Saúde Parte 3 - SQL
-- a) Crie as tabelas das seguintes entidades:
-- - Entidade: Funcionário
-- - Entidade: Nutricionista
-- - Entidade: Paciente
-- - Entidade: Consulta
-- - Entidade: Endereço

-- EXCLUINDO TABELAS:
DROP TABLE IF EXISTS CONSULTA;
DROP TABLE IF EXISTS NUTRICIONISTA;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS PACIENTE;
DROP TABLE IF EXISTS ENDERECO;

-- CRIANDO TABELAS:
CREATE TABLE IF NOT EXISTS ENDERECO(
	ID SERIAL PRIMARY KEY,
	LOGRADOURO VARCHAR(255),
	ESTADO VARCHAR(50),
	CIDADE VARCHAR(100),
	NUMERO VARCHAR(10),
	CEP VARCHAR(10)
);

CREATE TABLE FUNCIONARIO (
    ID SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
    MATRICULA VARCHAR(50) NOT NULL,
    TEMPO_EXPERIENCIA INT NOT NULL,
    ENDERECO_ID INTEGER REFERENCES ENDERECO(ID)
);

CREATE TABLE IF NOT EXISTS NUTRICIONISTA (
	ID SERIAL PRIMARY KEY,
	CRN VARCHAR(6) NOT NULL,
	ESPECIALIDADE VARCHAR(20)
) INHERITS (FUNCIONARIO);

CREATE TABLE IF NOT EXISTS PACIENTE (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	NASCIMENTO DATE,
	CPF VARCHAR(11),
	TELEFONE VARCHAR(15),
	EMAIL VARCHAR(50),
	ENDERECO_ID INTEGER REFERENCES ENDERECO(ID)
);

CREATE TABLE IF NOT EXISTS CONSULTA (
	ID SERIAL PRIMARY KEY,
	NUTRICIONISTA_ID INTEGER REFERENCES NUTRICIONISTA(ID) NOT NULL,
	PACIENTE_ID INTEGER REFERENCES PACIENTE(ID) NOT NULL,
	DATA_CONSULTA DATE,
	OBSERVACOES VARCHAR(255)
);

-- b) Insira, pelo menos, três registros para cada tabela.
-- ENDERECO
INSERT INTO ENDERECO (LOGRADOURO, ESTADO, CIDADE, NUMERO, CEP)
VALUES 
    ('Rua Lalala', 'SC', 'Florianópolis', '123', '01010-010'),
    ('Rua Lelele', 'SC', 'São José', '456', '20000-200'),
    ('Rua Lilili', 'SC', 'Palhoça', '789', '30000-300');

-- FUNCIONARIO
INSERT INTO FUNCIONARIO (NOME, MATRICULA, TEMPO_EXPERIENCIA, ENDERECO_ID)
VALUES 
    ('João Silva', 'FUNC001', 5, 1),
    ('Maria Souza', 'FUNC002', 8, 2),
    ('Carlos Oliveira', 'FUNC003', 3, 3);

-- NUTRICIONISTA
INSERT INTO NUTRICIONISTA (CRN, ESPECIALIDADE, NOME, MATRICULA, TEMPO_EXPERIENCIA, ENDERECO_ID)
VALUES 
    ('123456', 'Nutrição Clínica', 'João Silva', 'FUNC001', 5, 1),
    ('654321', 'Nutrição Esportiva', 'Maria Souza', 'FUNC002', 8, 2),
    ('987654', 'Nutrição Infantil', 'Carlos Oliveira', 'FUNC003', 3, 3);

-- PACIENTE
INSERT INTO PACIENTE (NOME, NASCIMENTO, CPF, TELEFONE, EMAIL, ENDERECO_ID)
VALUES 
    ('Ana Oliveira', '1990-05-15', '11122233344', '(11) 98765-4321', 'ana@example.com', 1),
    ('Pedro Santos', '1987-08-20', '55566677788', '(21) 99999-8888', 'pedro@example.com', 2),
    ('Mariana Costa', '2000-02-10', '99988877766', '(31) 77777-9999', 'mariana@example.com', 3);

-- CONSULTA
INSERT INTO CONSULTA (NUTRICIONISTA_ID, PACIENTE_ID, DATA_CONSULTA, OBSERVACOES)
VALUES 
    (1, 1, '2024-07-10', 'Paciente com dieta equilibrada.'),
    (2, 2, '2024-07-12', 'Aumentar consumo de proteínas.'),
    (3, 3, '2024-07-15', 'Acompanhar evolução da dieta.');

-- b) Atualize o telefone de um dos nutricionistas. (??? nutri não tem telefone)
UPDATE PACIENTE
SET
TELEFONE = '(48) 1234-4321'
WHERE
ID = 3;

-- c) Delete um registro da tabela.
DELETE FROM CONSULTA 
WHERE
 PACIENTE_ID = 2;


