-- [M205] Ex 2 - DDL das Tabelas
-- Crie DDL para as tabelas “Nutricionista”, “Paciente“, “Consulta“, 
-- conforme sua modelagem. O DDL inclui “create“ e “delete“.
-- EXCLUINDO TABELAS:
DROP TABLE IF EXISTS CONSULTA;

DROP TABLE IF EXISTS PACIENTE;

DROP TABLE IF EXISTS NUTRICIONISTA;

-- CRIANDO TABELAS:
CREATE TABLE IF NOT EXISTS NUTRICIONISTA (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	CRN VARCHAR(6) NOT NULL,
	ESPECIALIDADE VARCHAR(20),
	TEMPO_EXPERIENCIA INTEGER
);

CREATE TABLE IF NOT EXISTS PACIENTE (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	CPF VARCHAR(11),
	TELEFONE VARCHAR(11),
	EMAIL VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS CONSULTA (
	ID SERIAL PRIMARY KEY,
	ID_NUTRICIONISTA INTEGER NOT NULL,
	ID_PACIENTE INTEGER NOT NULL,
	DATA_CONSULTA DATE,
	OBSERVACOES VARCHAR(255)
);